$ErrorActionPreference='Stop'
Add-Type -Path (Join-Path $PSScriptRoot 'SemanticGuard.compiled.dll')
$results=[Collections.Generic.List[string]]::new()
function Check($name,$source,$draft,$expected){
    $actual=[DepoimentoLocal.Windows.SemanticGuard]::RepairSourceAnchors($source,$draft)
    if($actual -cne $expected){throw "$name`nExpected: $expected`nActual: $actual"}
    if([DepoimentoLocal.Windows.SemanticGuard]::RepairSourceAnchors($source,$actual) -cne $actual){throw "Not idempotent: $name"}
    $results.Add("PASS $name")
}
Check 'unique implicit narrator predicate' 'Eu não sei qual chave foi usada.' 'Não sabe qual chave foi usada.' 'O depoente não sabe qual chave foi usada.'
Check 'same predicate with two actors is ambiguous' 'A técnica não sabe qual chave foi usada. Eu não sei qual chave foi usada.' 'A técnica não sabe qual chave foi usada. Não sabe qual chave foi usada.' 'A técnica não sabe qual chave foi usada. Não sabe qual chave foi usada.'
Check 'named subject never replaced' 'Eu não sei qual chave foi usada.' 'A técnica não sabe qual chave foi usada.' 'A técnica não sabe qual chave foi usada.'
Check 'adverb after explicit narrator does not duplicate it' 'Eu também não vi o carro passar.' 'O depoente também não viu o carro passar.' 'O depoente também não viu o carro passar.'
Check 'adverb after named subject does not replace it' 'Eu também não vi o carro passar.' 'A técnica também não viu o carro passar.' 'A técnica também não viu o carro passar.'
Check 'coordinated narrator verbs' 'Depois eu fui buscar água e fiquei na cozinha.' 'Depois foi buscar água e ficou na cozinha.' 'Depois o depoente foi buscar água e ficou na cozinha.'
Check 'only modifies predicate not narrator' 'Sei onde foi, só não lembro a data.' 'Sabe onde foi, só não lembra a data.' 'O depoente sabe onde foi, o depoente só não lembra a data.'
Check 'also modifies predicate not narrator' 'Também não sei qual chave foi usada.' 'Também não sabe qual chave foi usada.' 'O depoente também não sabe qual chave foi usada.'
Check 'source explicit exclusive subject focus retained' 'Só eu não sei qual chave foi usada.' 'Só não sabe qual chave foi usada.' 'Só o depoente não sabe qual chave foi usada.'
Check 'source explicit additive subject focus retained' 'Também eu não sei qual chave foi usada.' 'Também não sabe qual chave foi usada.' 'Também o depoente não sabe qual chave foi usada.'
Check 'post-verbal narrator with predicate focus' 'Também ouvi a médica pedir silêncio.' 'Também ouviu o depoente a médica pedir silêncio.' 'O depoente também ouviu a médica pedir silêncio.'
Check 'source-proven post-verbal narrator' 'Ouvi a médica pedir silêncio.' 'Ouviu o depoente a médica pedir silêncio.' 'O depoente ouviu a médica pedir silêncio.'
Check 'source-proven post-verbal visual narrator' 'Eu não vi a funcionária retirar a bolsa.' 'Não viu o depoente a funcionária retirar a bolsa.' 'O depoente não viu a funcionária retirar a bolsa.'
Check 'post-verbal object of third party remains object' 'A médica ouviu o depoente pedir silêncio.' 'A médica ouviu o depoente pedir silêncio.' 'A médica ouviu o depoente pedir silêncio.'
Check 'same perception in source by multiple people is ambiguous' 'Eu ouvi a médica pedir silêncio. Ele ouviu a médica pedir silêncio.' 'Ouviu o depoente a médica pedir silêncio. Ele ouviu a médica pedir silêncio.' 'Ouviu o depoente a médica pedir silêncio. Ele ouviu a médica pedir silêncio.'
Check 'knowledge categories never interchanged' 'Eu não sei qual chave foi usada.' 'Não lembra qual chave foi usada.' 'Não lembra qual chave foi usada.'
Check 'quotation untouched' 'Eu não sei qual chave foi usada.' '“Não sabe qual chave foi usada.”' '“Não sabe qual chave foi usada.”'
Check 'same output frame across quotation segments is ambiguous' 'Eu não sei qual chave foi usada.' 'Não sabe qual chave foi usada. “pausa” Não sabe qual chave foi usada.' 'Não sabe qual chave foi usada. “pausa” Não sabe qual chave foi usada.'
Check 'explicit recipient from unique source frame' 'A Isabela falou para mim que faltava a assinatura.' 'A Isabela falou para ele que faltava a assinatura.' 'A Isabela falou para o depoente que faltava a assinatura.'
Check 'two source recipients are not merged' 'A Isabela falou para mim que faltava a assinatura. A técnica falou para ele que faltava a assinatura.' 'A Isabela falou para ele que faltava a assinatura. A técnica falou para ele que faltava a assinatura.' 'A Isabela falou para ele que faltava a assinatura. A técnica falou para ele que faltava a assinatura.'
Check 'restore explicit subordinate pronoun' 'Não sei o que ele pretende fazer depois.' 'Não sabe o que pretende fazer depois.' 'O depoente não sabe o que ele pretende fazer depois.'
Check 'two source subordinate frames are ambiguous' 'Não sei o que ele pretende fazer depois. Não sei o que pretende fazer depois.' 'Não sabe o que pretende fazer depois.' 'O depoente não sabe o que pretende fazer depois.'
Check 'restore complete approximate alternatives' 'Eu esperei uns oito ou nove minutos.' 'Esperou uns nove minutos.' 'O depoente esperou uns oito ou nove minutos.'
Check 'restore repeated approximate quantity' 'Eu esperei uns seis, seis e pouco minutos.' 'Esperou uns seis e pouco minutos.' 'O depoente esperou uns seis, seis e pouco minutos.'
Check 'another source interval prevents restoration' 'Eu esperei uns oito ou nove minutos. Ela esperou uns nove minutos.' 'Esperou uns nove minutos.' 'Esperou uns nove minutos.'
Check 'run-on estimate retains place and uncertainty' 'Eu voltei ali acho que era cedo.' 'O depoente voltou acredita que era cedo.' 'O depoente voltou ali; o depoente acredita que era cedo.'
Check 'explicit correction with repeated confirmation' 'Eu entrei... não, acho que a médica telefonou antes. É, a médica telefonou antes.' 'Entrou... Não, acredita que a médica telefonou antes. Sim, a médica telefonou antes.' 'O depoente acredita que a médica telefonou antes.'
Check 'temporal owner in explicit correction' 'Eu cheguei... não, acho que antes de chegar telefonou a médica. É, a médica telefonou antes.' 'Chegou... Não, acredita que a médica telefonou antes de sua chegada. Sim, a médica telefonou antes.' 'O depoente acredita que a médica telefonou antes da chegada do depoente.'
Check 'masculine temporal nominalization' 'Eu retornei... não, acho que depois de retornar telefonou a médica. É, a médica telefonou depois.' 'Retornou... Não, acredita que a médica telefonou depois do seu retorno. Sim, a médica telefonou depois.' 'O depoente acredita que a médica telefonou depois do retorno do depoente.'
Check 'another temporal owner is not reassigned' 'Eu cheguei... não, acho que antes de chegar telefonou a médica. É, a médica telefonou antes.' 'Chegou... Não, acredita que a médica telefonou antes da chegada da técnica. Sim, a médica telefonou antes.' 'O depoente acredita que a médica telefonou antes da chegada da técnica.'
Check 'no confirmation means no consolidation' 'Eu entrei... não, acho que a médica telefonou antes.' 'Entrou... Não, acredita que a médica telefonou antes.' 'Entrou... Não, o depoente acredita que a médica telefonou antes.'
Check 'different temporal confirmation is not redundant' 'Eu entrei... não, acho que a médica telefonou antes. É, a médica telefonou depois.' 'Entrou... Não, acredita que a médica telefonou antes. Sim, a médica telefonou depois.' 'Entrou... Não, o depoente acredita que a médica telefonou antes. Sim, a médica telefonou depois.'
# Round 3: residual first person, recipients, elliptical narrator, parallel corrections.
Check 'copied first-person verbs get narrator subject' 'Fechei a janela às nove. Não tranquei a porta.' 'Fechei a janela às nove. Não tranquei a porta.' 'O depoente fechou a janela às nove. O depoente não trancou a porta.'
Check 'irregular form after explicit narrator' 'Eu li o aviso na parede.' 'O depoente li o aviso na parede.' 'O depoente leu o aviso na parede.'
Check 'present form after explicit narrator' 'Eu trabalho na portaria.' 'O depoente trabalho na portaria.' 'O depoente trabalha na portaria.'
Check 'noun homograph untouched' 'O trabalho terminou cedo. Eu saí depois.' 'O trabalho terminou cedo. O depoente saiu depois.' 'O trabalho terminou cedo. O depoente saiu depois.'
Check 'adverbial before copied verb' 'Mais tarde recebi um bilhete.' 'Mais tarde recebi um bilhete.' 'Mais tarde o depoente recebeu um bilhete.'
Check 'spelling of -quei and -guei preterites' 'Toquei a campainha e entreguei o pacote.' 'Toquei a campainha e entreguei o pacote.' 'O depoente tocou a campainha e entregou o pacote.'
Check 'quoted first person untouched while narration converted' 'Heitor gritou: “fechei tudo”. Eu fechei a janela.' 'Heitor gritou: “fechei tudo”. Fechei a janela.' 'Heitor gritou: “fechei tudo”. O depoente fechou a janela.'
Check 'recipient restored after named speaker' 'A Clarice me contou que o portão estava aberto.' 'A Clarice contou que o portão estava aberto.' 'A Clarice lhe contou que o portão estava aberto.'
Check 'recipient restored after pronoun speaker' 'Depois ela me mostrou o recibo.' 'Depois ela mostrou o recibo.' 'Depois ela lhe mostrou o recibo.'
Check 'recipient turned into subject' 'Marta me disse que viria.' 'Marta o depoente disse que viria.' 'Marta lhe disse que viria.'
Check 'two recipients kept distinct' 'O porteiro Joaquim me contou que a vizinha lhe pediu a chave.' 'O porteiro Joaquim lhe contou que a vizinha lhe pediu a chave.' 'O porteiro Joaquim contou ao depoente que a vizinha lhe pediu a chave.'
Check 'participant own speech without recipient untouched' 'Marta disse que viria. Depois ela me disse que desistiu.' 'Marta disse que viria. Depois ela lhe disse que desistiu.' 'Marta disse que viria. Depois ela lhe disse que desistiu.'
Check 'elliptical reply after participant question' 'Heitor me perguntou se eu tinha a senha. Respondi que não.' 'Heitor lhe perguntou se o depoente tinha a senha. Respondeu que não.' 'Heitor lhe perguntou se o depoente tinha a senha. O depoente respondeu que não.'
Check 'cross-category draft not aligned by position' 'Não lembro da chave. Não sei da porta.' 'Não sabe da chave. Não lembra da porta.' 'Não sabe da chave. Não lembra da porta.'
Check 'same reply by participant stays ambiguous' 'Heitor respondeu que não. Respondi que não.' 'Heitor respondeu que não. Respondeu que não.' 'Heitor respondeu que não. Respondeu que não.'
Check 'relative clause narrator explicit' 'O síndico não estava na reunião que acompanhei.' 'O síndico não estava na reunião que acompanhou.' 'O síndico não estava na reunião que o depoente acompanhou.'
Check 'complement of narrator belief not duplicated' 'Acho que tranquei a porta.' 'O depoente acredita que trancou a porta.' 'O depoente acredita que trancou a porta.'
Check 'narrator rendered as ele restored' 'Na quarta eu estava de plantão.' 'Na quarta ele estava de plantão.' 'Na quarta o depoente estava de plantão.'
Check 'participant ele kept' 'Na quarta ele estava de plantão.' 'Na quarta ele estava de plantão.' 'Na quarta ele estava de plantão.'
Check 'parallel correction with quer dizer' 'Liguei para o gerente, quer dizer, para o supervisor do turno.' 'Ligou para o gerente, quer dizer, para o supervisor do turno.' 'O depoente ligou para o supervisor do turno.'
Check 'parallel false start with não' 'Cheguei na terça... não, na quarta-feira.' 'Chegou na terça... Não, na quarta-feira.' 'O depoente chegou na quarta-feira.'
Check 'non-parallel correction kept' 'Cheguei cedo... não, isso foi depois.' 'Chegou cedo... Não, isso foi depois.' 'O depoente chegou cedo... Não, isso foi depois.'
Check 'preposition contraction' 'Alguém falou atrás de mim.' 'Alguém falou atrás de o depoente.' 'Alguém falou atrás do depoente.'
Check 'infinitive subject keeps preposition' 'Antes de eu sair, a luz apagou.' 'Antes de o depoente sair, a luz apagou.' 'Antes de o depoente sair, a luz apagou.'
Check 'model attribution error not smoothed' 'A gerente pediu que eu fechasse o caixa.' 'O depoente pedi que o depoente fechasse o caixa.' 'O depoente pedi que o depoente fechasse o caixa.'
Check 'narrator moved from subordinate to main verb' 'A síndica me chamou. Expliquei que eu já tinha pago a taxa.' 'A síndica lhe chamou. Explicou que o depoente já tinha pago a taxa.' 'A síndica lhe chamou. O depoente explicou que já tinha pago a taxa.'
Check 'shared interaction without inferring participants' 'O zelador escutou nossa reunião.' 'O zelador escutou nossa reunião.' 'O zelador escutou a reunião de que o depoente participava.'
# Round 4: whole-sentence narrator subject, strict same-form verbs, narrator possessive.
Check 'whole narrator sentence after participant sentence' 'O Tiago procurou o carimbo. Eu não perguntei.' 'O Tiago procurou o carimbo. Não perguntou.' 'O Tiago procurou o carimbo. O depoente não perguntou.'
Check 'whole sentence disambiguates repeated verb frame' 'A diretora me chamou. Respondi que eu ainda não tinha o laudo. Depois respondi que não sabia.' 'A diretora lhe chamou. Respondeu que ainda não tinha o laudo. Depois o depoente respondeu que não sabia.' 'A diretora lhe chamou. O depoente respondeu que ainda não tinha o laudo. Depois o depoente respondeu que não sabia.'
Check 'same-form verb after sentence only of narrator' 'Recebi o envelope na portaria. Não disse nada sobre o conteúdo.' 'O depoente recebeu o envelope na portaria. Não disse nada sobre o conteúdo.' 'O depoente recebeu o envelope na portaria. O depoente não disse nada sobre o conteúdo.'
Check 'NEG same-form verb after sentence with participant subject' 'O Tiago mostrou o carimbo, mas eu não reconheci. Não disse que era falso.' 'O Tiago mostrou o carimbo, mas o depoente não reconheceu. Não disse que era falso.' 'O Tiago mostrou o carimbo, mas o depoente não reconheceu. Não disse que era falso.'
Check 'NEG same-form verb after sentence with pronoun' 'Recebi o envelope que ela trouxe. Não disse nada.' 'O depoente recebeu o envelope que ela trouxe. Não disse nada.' 'O depoente recebeu o envelope que ela trouxe. Não disse nada.'
Check 'NEG same-form verb after third-person verb' 'Vi que a luz apagou. Não sabia o motivo.' 'O depoente viu que a luz apagou. Não sabia o motivo.' 'O depoente viu que a luz apagou. Não sabia o motivo.'
Check 'NEG same-form verb at start of text' 'Disse que chegaria cedo.' 'Disse que chegaria cedo.' 'Disse que chegaria cedo.'
Check 'NEG same-form verb after same-form sentence' 'Estava na sala. Tinha medo.' 'Estava na sala. Tinha medo.' 'Estava na sala. Tinha medo.'
Check 'NEG repeated narrator sentence is ambiguous' 'Eu não perguntei. A Laura saiu. Eu não perguntei.' 'Não perguntou. A Laura saiu. Não perguntou.' 'Não perguntou. A Laura saiu. Não perguntou.'
Check 'narrator possessive named' 'O fiscal não assinou na minha presença.' 'O fiscal não assinou na sua presença.' 'O fiscal não assinou na presença do depoente.'
Check 'narrator possessive at sentence start' 'Meu relato termina aqui.' 'Seu relato termina aqui.' 'O relato do depoente termina aqui.'
Check 'NEG possessive kept when narrator is subject' 'Eu deixei minha mochila no balcão.' 'O depoente deixou sua mochila no balcão.' 'O depoente deixou sua mochila no balcão.'
Check 'NEG possessive kept when input has participant possessive' 'Ela pegou sua bolsa. Eu peguei minha bolsa.' 'Ela pegou sua bolsa. O depoente pegou sua bolsa.' 'Ela pegou sua bolsa. O depoente pegou sua bolsa.'
$results | Set-Content (Join-Path $PSScriptRoot 'reference-tests.txt')
$results
